rCSRCurumuyPiura:
  hostname: "10.134.13.221"
  username: "C27747"
  password: "IZanagI11."
  port: 22
  platform: "zte"
  data:
    real_alias: "rCSRCurumuyPiura"
    original_ip: "10.134.13.221"
  groups:
    - zte_routers


