AS_ARQ_Chala:
  hostname: "10.140.142.160"
  username: "C27747"
  password: "IZanagI11."
  port: 22
  platform: "zte"
  data:
    real_alias: "AS-ARQ-Chala"
    original_ip: "10.140.142.160"
  groups:
    - zte_routers


